### ISSUE TITLE
Releasing child coordinators

### ISSUE THREAD

**Issue by teameh** [igorkulman/iOSSampleApp#25]
Hi Igor, 

Thanks for sharing this repo, lots of good stuff! I wasn't sure where to ask you a question regarding the code so I'll add an issue, hope that's okay. 

Regarding releasing the child coordinators in the AppCoordinator, is there a reason you don't clean up the other child coordinator when switching view's? eg: `childCoordinators[.setup] = nil` 

And I was wondering, in the `FeedCoordinator`, you check if it's transitioning from the setup (with `!navigationController.viewControllers.isEmpty`. Wouldn't it be better to check this in the AppCoordinator to separate out the responsibilities better? The `FeedCoordinator` does not need to know anything about the setup right? 

Oh and I like your child-coordinator enums a lot, will use this for my next project! 

Cheers!

**Comment by igorkulman** [comment]
> Regarding releasing the child coordinators in the AppCoordinator, is there a reason you don't clean up the other child coordinator when switching view's? eg: `childCoordinators[.setup] = nil`

You are right, the `AppCoordinator` does not do any cleanup, I jut forgot about it there I guess. Thanks for noticing, I will add it.

> And I was wondering, in the `FeedCoordinator`, you check if it's transitioning from the setup (with `!navigationController.viewControllers.isEmpty`. Wouldn't it be better to check this in the AppCoordinator to separate out the responsibilities better? The `FeedCoordinator` does not need to know anything about the setup right?

I think this is just a problem with naming. The `FeedCoordinator`  always wants to push its first VC as the top level VC, so it clears the navigation stack if empty. I will make the naming better so there is no mention if setup.

**Comment by teameh** [comment]
That makes sense, thanks for clarifying
