### ISSUE TITLE
Project not building on Xcode 11.4

### ISSUE THREAD

**Issue by matghazaryan** [igorkulman/iOSSampleApp#27]
I am trying build project on Xcode 11.4

the carthage update failing you can see the below. 

I also have this warning "Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)."

Is there something we can do to fix it?

*** Checking out Nuke at "8.4.2"
*** Checking out Reusable at "4.1.1"
*** Checking out Quick at "v2.2.0"
*** Checking out FeedKit at "9.1.0"
*** xcodebuild output can be found in /var/folders/rx/mby_9bp11g98xr3ds6st2fxw0000gn/T/carthage-xcodebuild.L8y03x.log
*** Downloading Reusable.framework binary at "4.1.1"
*** Downloading RxSwift.framework binary at "Catalyst.1"
***  Skipped installing Reusable.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)."

    Falling back to building from the source
*** Building scheme "CRToast" in CRToast.xcodeproj
*** Building scheme "FeedKit iOS" in FeedKit.xcodeproj
*** Building scheme "Nimble-iOS" in Nimble.xcodeproj
*** Building scheme "Nuke" in Nuke.xcodeproj
*** Building scheme "Quick-iOS" in Quick.xcworkspace
*** Building scheme "Reusable-iOS" in ReusableDemo.xcworkspace
*** Building scheme "RxNuke" in RxNuke.xcodeproj
*** Building scheme "RxSwiftExt-iOS" in RxSwiftExt.xcworkspace
*** Building scheme "SpecLeaks" in SpecLeaks.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/mg/iOSProjects/iOSSampleApp/Sources/Carthage/Checkouts/specleaks/SpecLeaks.xcodeproj -scheme SpecLeaks -configuration Release -derivedDataPath /Users/mg/Library/Caches/org.carthage.CarthageKit/DerivedData/11.4_11E146/specleaks/0.1.8 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/rx/mby_9bp11g98xr3ds6st2fxw0000gn/T/specleaks SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/mg/iOSProjects/iOSSampleApp/Sources/Carthage/Checkouts/specleaks)

**Comment by igorkulman** [comment]
The warning about the RxSwift version is not a problem, it just tells you it will be built from source.

Specleaks failing to build is the actual problem. I will take a look, maybe an update to the libraries is needed.

**Comment by igorkulman** [comment]
Fixed now in `master`
