### ISSUE TITLE
Single responsability

### ISSUE THREAD

**Issue by JAIRMG** [igorkulman/iOSSampleApp#32]
I think that saving the user data, for example the `onBoardingData` should be responsability of the ViewModel, what do you think?. Nice project btw!

**Comment by igorkulman** [comment]
What do you mean by onboarding data? In the setup flow the ViewModel saves the RSS source the user selects: https://github.com/igorkulman/iOSSampleApp/blob/master/Sources/iOSSampleApp/Scenarios/Setup/ViewModels/SourceSelectionViewModel.swift#L80

**Comment by JAIRMG** [comment]
The `OnBoardingCoordinator` is saving the settings and the `SetOptionsViewModel` is practically empty, that's what I mean. This `self.dataManager.set(key: SettingKey.onBoardingData, value: data)` I think is a ViewModel responsability

**Comment by igorkulman** [comment]
There is no `OnBoardingCoordinator` in this code base.
